Repository fairhive-labs/docs, pull requests merged in 2023-10, with the labels that each got.

#7 refactor and rearrange sections in operational conditions phase
  airdrops/waitlist/README.md
  whitepaper/SUMMARY.md
  whitepaper/tokenomics/README.md
  whitepaper/tokenomics/demand.md
  whitepaper/tokenomics/operational-conditions.md
  whitepaper/tokenomics/operational-conditions/README.md
  whitepaper/tokenomics/operational-conditions/fellowship-formation-bidding.md
  whitepaper/tokenomics/operational-conditions/initiator-project-description-posting.md
  whitepaper/tokenomics/operational-conditions/project-execution-evaluation.md
  whitepaper/tokenomics/operational-conditions/reward-fee-distribution.md
  whitepaper/tokenomics/operational-conditions/staking-payment-locks.md
  whitepaper/tokenomics/token-details.md
  whitepaper/tokenomics/utility.md
  whitepaper/tokenomics/value-captured.md
  whitepaper/why/future-of-work-is-a-paradigm-shift-underpinned-by-self-employment.md
  whitepaper/why/new-generations-have-different-expectations.md
  whitepaper/why/traditional-economy-depends-on-fossils-fuels.md
  whitepaper/why/wealth-inequality-is-growing-globally.md
Labels: documentation, duplicate, enhancement, good first issue, help wanted

#22 detail token sales
  whitepaper/tokenomics/token-distribution.md
Labels: documentation, good first issue, help wanted

#23 document architecture overview
  whitepaper/architecture.md
Labels: documentation, good first issue, help wanted

#25 document categories
  airdrops/waitlist/roles-categories.md
Labels: documentation, duplicate, enhancement, good first issue

#34 refactor waitlist pages into single one
  airdrops/.gitbook/assets/Pre-registration_Workflow_v1.1.png
  airdrops/README.md
  airdrops/SUMMARY.md
  airdrops/waitlist/future-improvements-alpha.md
  airdrops/waitlist/roles-categories.md
  airdrops/waitlist/sequence-diagram.md
  airdrops/waitlist/step-1-registration.md
  airdrops/waitlist/step-2-activation.md
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted

#37 detail workflow
  airdrops/README.md
Labels: documentation, duplicate, enhancement, good first issue

#39 team
  whitepaper/SUMMARY.md
  whitepaper/fairhive-labs-team.md
Labels: documentation, enhancement, good first issue, help wanted
